version: 2.1
jobs:
  build_and_push_ecr:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: Login to ECR
          command: |
            aws ecr get-login-password --region YOUR_AWS_REGION | docker login --username AWS --password-stdin YOUR_AWS_ACCOUNT_ID.dkr.ecr.YOUR_AWS_REGION.amazonaws.com
      - run:
          name: Build Docker image
          command: docker build -t YOUR_ECR_REPO_NAME:latest .
      - run:
          name: Tag Docker image
          command: docker tag YOUR_ECR_REPO_NAME:latest YOUR_AWS_ACCOUNT_ID.dkr.ecr.YOUR_AWS_REGION.amazonaws.com/YOUR_ECR_REPO_NAME:latest
      - run:
          name: Push Docker image to ECR
          command: docker push YOUR_AWS_ACCOUNT_ID.dkr.ecr.YOUR_AWS_REGION.amazonaws.com/YOUR_ECR_REPO_NAME:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push_ecr:
          context: aws-ecr-context